obj-m += sx1276-spidevs.o
sx1276-spidevs-objs := sx1276-spidev.o sx1276-board.o utilities.o sx1276.o sx1276-cdev.o proc.o NodeDatabase.o LoRaMacCrypto.o aes.o cmac.o Radio.o debug.o Server.o LoRaWAN.o