#!/bin/sh /etc/rc.common
# "new" style init scriptt
# Look at /lib/functions/service.sh on a running system for explanations of what other SERVICE_
# options you can use, and when you might want them.

START=80
APP=node-manage
SERVICE_WRITE_PID=1
SERVICE_DAEMONIZE=1

start() {
	widora_mode router
        service_start /bin/$APP
}

stop() {
        service_stop /bin/$APP
}

restart() {
	service_stop /bin/$APP
        service_start /bin/$APP
}
